Repository dictyBase/migration-data, pull requests merged in 2022-01, with the labels that each got.

#45 Add files dicty environment upload
  ontologies/dicty_environment.obo
Labels: size/M

#46 Add files via upload
  ontologies/strain_characteristics.obo
Labels: size/L

#47 Add files via upload
  ontologies/dicty_strain_characteristics.obo
Labels: size/M

#48 Add files via upload
  ontologies/dicty_mutagenesis_method.obo
Labels: size/S

#49 Add files via upload
  ontologies/dicty_phenotypes.obo
Labels: size/XS

#50 Add files via upload
  ontologies/dicty_environment.obo
Labels: size/S

#51 Pulling pfey03-patch-10 into develop
  ontologies/dicty_plasmid_inventory.obo
  ontologies/dicty_storage_condition.obo
Labels: size/M

#53 Pulling pfey03-patch-12 into develop
  ontologies/dicty_plasmid_keywords.obo
Labels: size/M

#54 Add files via upload
  ontologies/dicty_strain_inventory.obo
Labels: size/S

#55 Pulling pfey03-patch-14 into develop
  ontologies/dicty_assay.obo
Labels: size/L

#56 Add files via upload
  ontologies/dicty_genetic_modification.obo
  ontologies/dicty_mutagenesis_method.obo
Labels: size/S

#57 Add files via upload
  ontologies/dicty_annotation.obo
Labels: size/S

#58 Pulling pfey03-patch-17 into develop
  ontologies/dicty_environment.obo
  ontologies/dicty_strain_characteristics.obo
Labels: size/XS

#59 Add files via upload
  ontologies/dicty_environment.obo
Labels: size/XS
